name: Upload to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: pressable/github-action-sftp@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          localDir: ./
          remoteDir: /home/youngau/public_html
          synchronize: true
